package spp.businesslogic.enums;

public enum DocumentType {
    CLASS_SCHEDULE,
    ACTIVITIES_SCHEDULE,
    PARTIAL_REPORT,
    MONTHLY_REPORT,
    ACTIVITIES_PLAN,
    SELF_EVALUATION,
    EVALUATION_LINKED_ORGANIZATION,
    FINAL_REPORT,
    PSP,
    INDICATOR_REPORT,
    PRESENTATION_TEMPLATE,
    RELEASE_LETTER
}